[package]
name = "mdtranslation"
version = "0.1.0"
authors = ["CrLF0710 <crlf0710@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[workspace]
members = ["mdtranslation-cli", "mdbook-translation"]

[dependencies]
pulldown-cmark = "0.8.0"
